import {changeLanguage} from 'i18next';
import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({
  en: {
    welcome: 'Welcome',
    welcometoh: 'Welcome to HiranyaGarbha',
    subText: "India's Most Trusted \nOnline Garbhsanskar Community",
    changeLanguage: 'Change Language',
    Hi: 'Hi',
    howCanHelp: 'How can we help you?',
    chatWithUs: 'Chat with us',
    support: 'Support',
    enterYourEmail: 'Enter your E-mail',
    enterYourPass: 'Enter your Password',
    password6Digit: 'Password must be at least 6 characters',
    pleaseValidEMail: 'Please enter a valid E-mail',
    wesentOTP: 'We sent the OTP to',
    ResendOTP: 'Resend OTP',
    Email: 'E-mail',
    Password: 'Password',
    loginwithotp: 'Login with OTP',
    loginwithpass: 'Login with Password',
    loginwithwhatsapp: 'Login with WhatsApp',
    loginwithmobile: 'Login with Email',
    verifyEmail: 'Verify your Email',
    addPhoneNumber: "Add your Email. We'll send you a verification code.",
    enterPassword:
      'Enter your registered mobile number and password to access the app.',
    login: 'Login',
    sendotp: 'Send OTP',
    Profile: 'Profile',
    Premium: 'Premium',
    myProfile: 'My Profile',
    ProductsPlans: 'Products & Plans',
    MyOrder: 'My Order',
    changeLanguage: 'Change Language',
    PrivacyPolicy: 'Privacy Policy',
    TermsCondition: 'Terms & Condition',
    Subscription: 'Subscription T&C',
    Logout: 'Logout Account',
    Goodnoon: 'Good Afternoon',
    Goodmorning: 'Good Morning',
    Goodevening: 'Good Evening',
    yourChild: 'Best Investment You can make for Your Child, Your Future',
    setting: 'Setting',
    signup: 'Sign Up',
    fullname: 'Full Name',
    enterYourFullname: 'Enter your Full Name',
    userMo: 'Mobile No.',
    enterusermo: 'Enter your Mobile No',
    chooseyourePreferred: 'Choose your Preferred Language',
    chooseLanguage: 'Choose Language',
    bestinvestement: 'Best Investment You can make for',
    yourchild: 'Your Child, Your Future',
    gold: 'Gold',
    silver: 'Silver',
    platinum: 'Platinum',
    off: 'off',
    premiumtitletxt:
      'Get Hiranyagarbha Book and Daily 25+ Activities for Unborn Childs PQ, IQ, EQ, & SQ Development',
    helpno: 'Helpline No. : ',
    pay: 'Pay',
    LMP:"Enter your last menstrual period",
    EDD:"Enter your Expected delivery date",
    enterYourFullName:"Enter Your FullName"
  },
  hi: {
    welcome: 'स्वागत है',
    welcometoh: 'हिरण्यगर्भ में आपका स्वागत है',
    subText: 'भारत का सबसे भरोसेमंद \nऑनलाइन गर्भसंस्कार समुदाय',
    changeLanguage: 'भाषा बदलें',
    Hi: 'नमस्ते',
    wesentOTP: 'हमने ओटीपी भेज दिया',
    ResendOTP: 'ओटीपी दोबारा भेजें',
    howCanHelp: 'हम आपकी कैसे मदद कर सकते हैं?',
    chatWithUs: 'हमारे साथ चैट करें',
    verifyEmail: 'अपना ईमेल जांचे',
    enterYourEmail: 'अपना ईमेल दर्ज करें',
    enterYourPass: 'अपना पासवर्ड दर्ज करें',
    password6Digit: 'पासवर्ड कम से कम 6 अंकों का होना चाहिए',
    pleaseValidEMail: 'कृपया एक मान्य ईमेल दर्ज करें',
    Email: 'ईमेल',
    Password: 'पासवर्ड',
    support: 'सहायता',
    sendotp: 'ओटीपी भेजें',
    login: 'लॉगिन',
    loginwithotp: 'ओटीपी से लॉग इन करें',
    loginwithpass: 'पासवर्ड से लॉग इन करें',
    setting: 'सेटिंग',
    loginwithwhatsapp: 'व्हाट्सएप से लॉग इन करें',
    loginwithmobile: 'ईमेल से लॉगिन करें',
    addPhoneNumber: 'अपना ईमेल जोड़ें. हम आपको एक सत्यापन कोड भेजेंगे.',
    enterPassword:
      'ऐप तक पहुंचने के लिए अपना पंजीकृत मोबाइल नंबर और पासवर्ड दर्ज करें।',
    Profile: 'प्रोफ़ाइल',
    Premium: 'अधिमूल्य',
    myProfile: 'मेरी प्रोफाइल',
    ProductsPlans: 'उत्पादन एवं योजनाएँ',
    MyOrder: 'मेरे आदेश',
    changeLanguage: 'भाषा बदलें',
    PrivacyPolicy: 'गोपनीयता नीति',
    TermsCondition: 'नियम व शर्त',
    Subscription: 'सदस्यता नियम एवं शर्तें',
    Logout: 'लॉगआउट खाता',
    Goodnoon: 'शुभ दोपहर',
    Goodmorning: 'शुभ प्रभात',
    Goodevening: 'शुभ संध्या',
    yourChild:
      'सर्वोत्तम निवेश जो आप अपने बच्चे, अपने भविष्य के लिए कर सकते हैं',
    signup: 'साइन अप',
    fullname: 'पूर्ण नाम',
    enterYourFullname: 'अपना पूर्ण नाम दर्ज करें',
    userMo: 'मोबाइल नंबर',
    enterusermo: 'अपना मोबाइल नंबर दर्ज करें',
    chooseyourePreferred: 'अपनी पसंदीदा भाषा चुनें',
    chooseLanguage: 'भाषा चुनें',
    bestinvestement: 'आपके लिए सबसे अच्छा निवेश',
    yourchild: 'आपका बच्चा, आपका भविष्य',
    gold: 'सोना',
    silver: 'चांदी',
    platinum: 'प्लैटिनम',
    off: 'ऑफ़',
    premiumtitletxt:
      'हिरण्यगर्भा पुस्तक प्राप्त करें और गर्भस्थ शिशुओं के PQ, IQ, EQ और SQ विकास के लिए 25+ दैनिक गतिविधियाँ',
    helpno: 'हेल्पलाइन नंबर : ',
    pay: 'भुगतान',
    LMP: 'अपना आखिरी मासिक धर्म की तारीख दर्ज करें',
    EDD: 'अपनी अनुमानित प्रसव तिथि दर्ज करें',
  },
  gu: {
    welcome: 'સ્વાગત છે',
    welcometoh: 'હિરણ્યગર્ભમાં આપનું સ્વાગત છે',
    subText: 'ભારતનું સૌથી વિશ્વસનીય \nઓનલાઇન ગર્ભસંस्कार સમુદાય',
    changeLanguage: 'ભાષા બદલોઃ',
    Hi: 'હાય',
    wesentOTP: 'અમે OTP મોકલી દીધો છે',
    ResendOTP: 'OTP ફરીથી મોકલો',
    howCanHelp: 'અમારે તમારી કેવી રીતે મદદ કરી શકે છે?',
    chatWithUs: 'અમારા સાથે વાત કરો',
    verifyEmail: 'તમારો ઈમેલ ચકાસો',
    enterYourEmail: 'તમારો ઈમેલ દાખલ કરો',
    enterYourPass: 'તમારો પાસવર્ડ દાખલ કરો',
    password6Digit: 'પાસવર્ડમાં ઓછામાં ઓછા 6 અંક હોવા જોઈએ',
    pleaseValidEMail: 'કૃપા કરીને માન્ય ઈમેલ દાખલ કરો',
    Email: 'ઈમેલ',
    setting: 'સેટિંગ  ',
    Password: 'પાસવર્ડ',
    support: 'મદદ',
    sendotp: 'OTP મોકલવો',
    login: 'લૉગિન',
    loginwithotp: 'OTP સાથે લૉગિન કરો',
    loginwithpass: 'પાસવર્ડથી લૉગિન કરો',
    loginwithwhatsapp: 'વોટ્સએપ સાથે લૉગિન કરો',
    loginwithmobile: 'ઈમેલ સાથે લૉગિન કરો',
    addPhoneNumber: 'તમારો ઈમેલ ઉમેરો. અમે તમને એક પુષ્ટિ કોડ મોકલીશું.',
    enterPassword:
      'એપ્લિકેશનનો ઉપયોગ કરવા માટે તમારો નોંધણી કરેલો મોબાઇલ નંબર અને પાસવર્ડ દાખલ કરો.',
    Profile: 'પ્રોફાઈલ',
    Premium: 'પ્રીમિયમ',
    myProfile: 'મારું પ્રોફાઈલ',
    ProductsPlans: 'ઉત્પાદનો અને યોજનાઓ',
    MyOrder: 'મારો આદેશ',
    changeLanguage: 'ભાષા બદલો',
    PrivacyPolicy: 'ગોપનીયતા નીતિ',
    TermsCondition: 'શરતો અને નિયમો',
    Subscription: 'સદસ્યતા શરતો અને નિયમો',
    Logout: 'લૉગઆઉટ એકાઉન્ટ',
    Goodnoon: 'શુભ બપોર',
    Goodmorning: 'શુભ સવાર',
    Goodevening: 'શુભ સાંજ',
    yourChild: 'તમારા બાળક માટે શ્રેષ્ઠ રોકાણ, તમારો ભવિષ્ય',
    signup: 'સાઇન અપ',
    fullname: 'પૂર્ણ નામ',
    enterYourFullname: 'તમારું સંપૂર્ણ નામ દાખલ કરો',
    userMo: 'મોબાઈલ નંબર',
    enterusermo: 'તમારો મોબાઇલ નંબર દાખલ કરો',
    chooseyourePreferred: 'તમારી પસંદની ભાષા પસંદ કરો',
    chooseLanguage: 'ભાષા પસંદ કરો',
    bestinvestement: 'તમારા માટે શ્રેષ્ઠ રોકાણ',
    yourchild: 'તમારું બાળક, તમારું ભવિષ્ય',
    gold: 'સોનું',
    silver: 'ચાંદી',
    platinum: 'પ્લેટિનમ',
    off: 'ઓફ',
    premiumtitletxt:
      'હિરણ્યગર્ભા પુસ્તક મેળવો અને ગર્ભવતી બાળકોએ માટે PQ, IQ, EQ અને SQ વિકાસ માટે દરરોજ 25+ પ્રવૃત્તિઓ',
    helpno: 'હેલ્પલાઇન નંબર : ',
    pay: 'ચૂકવણી',
    LMP: 'તમારો છેલ્લો માસિક પીરિયડ દાખલ કરો',
    EDD: 'તમારા અપેક્ષિત જન્મ તારીખ દાખલ કરો',
  },
  as: {
    welcome: 'স্বাগতম',
    welcometoh: 'হিৰণ্য গাৰ্ভত আপোনাৰ স্বাগতম',
    subText: 'ভাৰতৰ আটাইতকৈ বিশ্বাসযোগ্য \nঅনলাইন গাৰ্ভসংস্কাৰ কমিউনিটি',
    changeLanguage: 'ভাষা সলনি কৰক',
    Hi: 'হাই',
    howCanHelp: 'আমিৰে আপোনাৰ সহায় কৰিব পাৰিম নে?',
    chatWithUs: 'আমাৰ সৈতে চেট কৰক',
    support: 'সহায়',
    enterYourEmail: 'আপোনাৰ ই-মেইল ঠিকনা সন্নিৱিষ্ট কৰক',
    enterYourPass: 'আপোনাৰ পাছৱৰ্ড সন্নিৱিষ্ট কৰক',
    password6Digit: "পাছৱৰ্ডৰ পৰিমাণ কমেও ৬ আখৰ হ'ব লাগিব",
    pleaseValidEMail: 'দয়া কৰি এক বৈধ ই-মেইল ঠিকনা সন্নিৱিষ্ট কৰক',
    wesentOTP: 'আমিয়ে OTP পঠাইছে',
    ResendOTP: 'OTP পুনৰ পঠাওক',
    Email: 'ই-মেইল',
    Password: 'পাছৱৰ্ড',
    loginwithotp: 'OTPৰ পৰা লগইন কৰক',
    loginwithpass: 'পাছৱৰ্ডৰ পৰা লগইন কৰক',
    loginwithwhatsapp: 'ৱটসএপৰ পৰা লগইন কৰক',
    loginwithmobile: 'ই-মেইলৰ পৰা লগইন কৰক',
    verifyEmail: 'আপোনাৰ ই-মেইল প্ৰমাণিত কৰক',
    addPhoneNumber:
      'আপোনাৰ ই-মেইল ঠিকনা সন্নিৱিষ্ট কৰক। আমি আপোনাৰ প্ৰমাণীকৰণ কোড পঠাম',
    enterPassword:
      'আপোনাৰ ৰেজিষ্টাৰ্ড মোবাইল নম্বৰ আৰু পাছৱৰ্ড সন্নিৱিষ্ট কৰক।',
    login: 'লগইন',
    sendotp: 'OTP পঠাওক',
    Profile: "প্ৰ'ফাইল",
    Premium: 'প্ৰিমিয়াম',
    myProfile: "মোৰ প্ৰ'ফাইল",
    ProductsPlans: 'প্ৰডাক্ট আৰু পৰিকল্পনা',
    MyOrder: "মোৰ অ'ৰ্ডাৰ",
    changeLanguage: 'ভাষা সলনি কৰক',
    PrivacyPolicy: 'গোপনীয়তা নীতি',
    TermsCondition: 'শৰ্তৰ অৱস্থা',
    Subscription: 'সাবস্ক্ৰিপশ্যন T&C',
    Logout: 'আউট লগ',
    Goodnoon: 'সুপ্ৰভাত',
    Goodmorning: 'শুভ সকাল',
    Goodevening: 'শুভ সন্ধ্যা',
    yourChild: 'আপোনাৰ শিশু, আপোনাৰ ভবিষ্যৎ বাবে সৰ্বশ্ৰেষ্ঠ বিনিয়োগ',
    setting: 'ছেটিং',
    signup: 'সাইন আপ',
    fullname: 'সম্পূৰ্ণ নাম',
    enterYourFullname: 'আপোনাৰ সম্পূৰ্ণ নাম সন্নিৱিষ্ট কৰক',
    userMo: "ম'বাইল নম্বৰ",
    enterusermo: "আপোনাৰ ম'বাইল নম্বৰ সন্নিৱিষ্ট কৰক",
    chooseyourePreferred: 'আপোনাৰ পছন্দৰ ভাষা বাছনি কৰক',
    chooseLanguage: 'ভাষা বাছনি কৰক',
    bestinvestement: 'আপোনাৰ বাবে সৰ্বশ্ৰেষ্ঠ বিনিয়োগ',
    yourchild: 'আপোনাৰ সন্তান, আপোনাৰ ভবিষ্যৎ',
    gold: 'সোনা',
    silver: 'ৰূপা',
    platinum: 'প্লাটিনাম',
    off: 'অফ',
    premiumtitletxt:
      'হিৰণ্যগর্ভা কিতাপ লৈ আহক আৰু গৰ্ভৱস্থ শিশুৰ PQ, IQ, EQ, আৰু SQ বিকাশৰ বাবে ২৫+ দৈনিক কাৰ্যসূচী',
    helpno: 'হেল্পলাইন নম্বর : ',
    pay: 'পে',
    LMP: 'আপনার শেষ মাসিক ঋতু দিন লিখুন',
    EDD: 'আপনার প্রত্যাশিত প্রসব তারিখ লিখুন',
  },
  kok: {
    welcome: 'वेलकम',
    welcometoh: 'हिरण्य गर्भांत आपला वेलकम',
    subText: 'भारताचें सगळ्यात विश्वासार्ह \nऑनलाइन गर्भसंस्कार कम्युनिटी',
    changeLanguage: 'भाषा बदला',
    Hi: 'हाय',
    howCanHelp: 'आम्ही तुमका किते मदत करू शकतां?',
    chatWithUs: 'आमच्याशी चॅट करा',
    support: 'सपोर्ट',
    enterYourEmail: 'तुमका ई-मेल ठेवा',
    enterYourPass: 'तुमका पासवर्ड ठेवा',
    password6Digit: 'पासवर्ड किमान ६ अंकी असावा',
    pleaseValidEMail: 'कृपया एक वैध ई-मेल ठेवा',
    wesentOTP: 'आम्ही OTP पाठविलें',
    ResendOTP: 'OTP पुन्हा पाठवा',
    Email: 'ई-मेल',
    Password: 'पासवर्ड',
    loginwithotp: 'OTP वापरून लॉगिन करा',
    loginwithpass: 'पासवर्ड वापरून लॉगिन करा',
    loginwithwhatsapp: 'व्हाट्सअ‍ॅप वापरून लॉगिन करा',
    loginwithmobile: 'ई-मेल वापरून लॉगिन करा',
    verifyEmail: 'तुमका ई-मेल सत्यापित करा',
    addPhoneNumber: 'तुमका ई-मेल ठेवा. आम्ही तुमका एक सत्यापन कोड पाठवु',
    enterPassword: 'तुमच्या नोंदणी केलेल्या मोबाइल नंबर आणि पासवर्ड ठेवा.',
    login: 'लॉगिन',
    sendotp: 'OTP पाठवा',
    Profile: 'प्रोफाईल',
    Premium: 'प्रिमियम',
    myProfile: 'माझा प्रोफाईल',
    ProductsPlans: 'प्रोडक्ट्स आणि योजना',
    MyOrder: 'माझं ऑर्डर',
    changeLanguage: 'भाषा बदला',
    PrivacyPolicy: 'गोपनीयता धोरण',
    TermsCondition: 'अटी आणि शर्त',
    Subscription: 'साबस्क्रिप्शन T&C',
    Logout: 'आउट लॉगिन',
    Goodnoon: 'शुभ दुपार',
    Goodmorning: 'शुभ सकाळ',
    Goodevening: 'शुभ संध्याकाळ',
    yourChild: 'तुमच्या मुलासाठी, तुमच्या भविष्याच्या सर्वोत्तम गुंतवणूक',
    setting: 'सेटिंग',
    signup: 'साइन अप',
    fullname: 'पूर्ण नाव',
    enterYourFullname: 'तुमचं पूर्ण नाव ठेवा',
    userMo: 'मोबाइल नंबर',
    enterusermo: 'तुमका मोबाइल नंबर ठेवा',
    chooseyourePreferred: 'तुमका तुमचेर आवडलेली भाषा निवडा',
    chooseLanguage: 'भाषा निवडा',
    bestinvestement: 'तुमका तुमका सगळे जास्त गुंतवणूक',
    yourchild: 'तुमका तुमका मुल, तुमका भविष्य',
    gold: 'सोनं',
    silver: 'चांदी',
    platinum: 'प्लॅटिनम',
    off: 'ऑफ',
    premiumtitletxt:
      'हिरण्यगर्भा पुस्तक मिळवा आनी गार्भवती बाल्यांचो PQ, IQ, EQ आनी SQ विकासाक 25+ दररोजच्या क्रिया',
    helpno: 'हेल्पलाइन नंबर : ',
    pay: 'পে',
    LMP: 'तुमच्या शेवटच्या मासिक पाळीचा दिवस प्रविष्ट करा',
    EDD: 'तुमच्या अपेक्षित प्रसूत दिनांक प्रविष्ट करा',
  },
  kn: {
    welcome: 'ಸ್ವಾಗತ',
    welcometoh: 'ಹಿರಣ್ಯ ಗರ್ಭಕ್ಕೆ ಸ್ವಾಗತ',
    subText: 'ಭಾರತದ ಅತ್ಯಂತ ವಿಶ್ವಾಸಾರ್ಹ \nಆನ್‌ಲೈನ್ ಗರ್ಭಸಂಸ್ಕಾರ ಸಮುದಾಯ',
    changeLanguage: 'ಭಾಷೆ ಬದಲಿಸಿ',
    Hi: 'ಹಾಯ್',
    howCanHelp: 'ನಾವು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?',
    chatWithUs: 'ನಮ್ಮೊಡನೆ ಚಾಟ್ ಮಾಡಿ',
    support: 'ಸಹಾಯ',
    enterYourEmail: 'ನಿಮ್ಮ ಇ-ಮೇಲ್ ನಮೂದಿಸಿ',
    enterYourPass: 'ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
    password6Digit: 'ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 6 ಅಂಕಿಗಳು ಇರಬೇಕು',
    pleaseValidEMail: 'ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ ಇ-ಮೇಲ್ ನಮೂದಿಸಿ',
    wesentOTP: 'ನಾವು OTP ಕಳುಹಿಸೆವು',
    ResendOTP: 'OTP ಪುನಃ ಕಳುಹಿಸು',
    Email: 'ಇ-ಮೇಲ್',
    Password: 'ಪಾಸ್‌ವರ್ಡ್',
    loginwithotp: 'OTP ಮೂಲಕ ಲಾಗಿನ್ ಮಾಡಿ',
    loginwithpass: 'ಪಾಸ್‌ವರ್ಡ್ ಮೂಲಕ ಲಾಗಿನ್ ಮಾಡಿ',
    loginwithwhatsapp: 'ವಾಟ್ಸಾಪ್ ಮೂಲಕ ಲಾಗಿನ್ ಮಾಡಿ',
    loginwithmobile: 'ಇ-ಮೇಲ್ ಮೂಲಕ ಲಾಗಿನ್ ಮಾಡಿ',
    verifyEmail: 'ನಿಮ್ಮ ಇ-ಮೇಲ್ ಪರಿಶೀಲಿಸಿ',
    addPhoneNumber: 'ನಿಮ್ಮ ಇ-ಮೇಲ್ ಸೇರಿಸಿ. ನಾವು ನಿಮಗೆ ದೃಢೀಕರಣ ಕೋಡ್ ಕಳುಹಿಸೋಣ.',
    enterPassword:
      'ಆಪ್‌ಗೆ ಪ್ರವೇಶಿಸಲು ನಿಮ್ಮ ನೋಂದಣಿಯಾದ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ.',
    login: 'ಲಾಗಿನ್',
    sendotp: 'OTP ಕಳುಹಿಸು',
    Profile: 'ಪ್ರೊಫೈಲ್',
    Premium: 'ಪ್ರೀಮಿಯಮ್',
    myProfile: 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    ProductsPlans: 'ಉತ್ಪನ್ನಗಳು ಮತ್ತು ಯೋಜನೆಗಳು',
    MyOrder: 'ನನ್ನ ಆರ್ಡರ್',
    changeLanguage: 'ಭಾಷೆ ಬದಲಿಸಿ',
    PrivacyPolicy: 'ಗೋಪನೀಯತೆ ನೀತಿ',
    TermsCondition: 'ನಿಬಂಧನೆಗಳು ಮತ್ತು ಷರತ್ತುಗಳು',
    Subscription: 'ಸಬ್‌ಸ್ಕ್ರಿಪ್ಶನ್ T&C',
    Logout: 'ಖಾತೆಯಿಂದ ಲಾಗ್‌ಔಟ್',
    Goodnoon: 'ಶುಭ ದुपಾರಿ',
    Goodmorning: 'ಶುಭೋದಯ',
    Goodevening: 'ಶುಭ ಸಂಜೆ',
    yourChild:
      'ನಿಮ್ಮ ಮಕ್ಕಳಿಗೆ ನೀವು ಮಾಡಬಹುದಾದ ಅತ್ಯುತ್ತಮ ಹೂಡಿಕೆಯಾಗಿದ್ದು, ನಿಮ್ಮ ಭವಿಷ್ಯವೂ ಆಗಿದೆ',
    setting: 'ಸೆಟಿಂಗ್',
    signup: 'ಸೈನ್ ಅಪ್',
    fullname: 'ಪೂರ್ಣ ಹೆಸರು',
    enterYourFullname: 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು ನಮೂದಿಸಿ',
    userMo: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    enterusermo: 'ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
    chooseyourePreferred: 'ನಿಮ್ಮ ಇಚ್ಛಿತ ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    chooseLanguage: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    bestinvestement: 'ನಿಮ್ಮಿಗಾಗಿ ಅತ್ಯುತ್ತಮ ಹೂಡಿಕೆ',
    yourchild: 'ನಿಮ್ಮ ಮಗುವು, ನಿಮ್ಮ ಭವಿಷ್ಯ',
    gold: 'ಸೋನು',
    silver: 'ಚಿನ್ನಿ',
    platinum: 'ಪ್ಲಾಟಿನಮ್',
    off: 'ಆಫ್',
    premiumtitletxt:
      'ಹಿರಣ್ಯಗರ್ಭ ಪುಸ್ತಕವನ್ನು ಪಡೆಯಿರಿ ಮತ್ತು ಗರ್ಭಿಣಿ ಮಕ್ಕಳ PQ, IQ, EQ, ಮತ್ತು SQ ಅಭಿವೃದ್ಧಿಗಾಗಿ ದಿನಕ್ಕೆ 25+ ಚಟುವಟಿಕೆಗಳನ್ನು',
    helpno: 'ಹೆಲ್ಪ್‌ಲೈನ್ ಸಂಖ್ಯೆ : ',
    pay: 'ಪೇ',
    LMP: 'ನಿಮ್ಮ ಕೊನೆಯ ಮಾಸಿಕ ಅವಧಿಯನ್ನು ನಮೂದಿಸಿ',
    EDD: 'ನಿಮ್ಮ ನಿರೀಕ್ಷಿತ ಡೆಲಿವರಿ ದಿನಾಂಕವನ್ನು ನಮೂದಿಸಿ',
  },
  ml: {
    welcome: 'സ്വാഗതം',
    welcometoh: 'ഹിരണ്യ ഗർഭത്തിൽ സ്വാഗതം',
    subText: 'ഭാരതത്തിലെ ഏറ്റവും വിശ്വസനീയമായ \nഓൺലൈൻ ഗർഭസംസ്കാർ സമുഹം',
    changeLanguage: 'ഭാഷ മാറ്റുക',
    Hi: 'ഹായ്',
    howCanHelp: 'നാം നിങ്ങളെ എങ്ങനെ സഹായിക്കാമെന്ന് പറയൂ?',
    chatWithUs: 'നമോടൊപ്പം ചാറ്റ് ചെയ്യൂ',
    support: 'സഹായം',
    enterYourEmail: 'നിങ്ങളുടെ ഇ-മെയിൽ അഡ്രസ് നൽകുക',
    enterYourPass: 'നിങ്ങളുടെ പാസ്വേഡ് നൽകുക',
    password6Digit: 'പാസ്വേഡുകൾ കുറഞ്ഞത് 6 അക്കങ്ങളായിരിക്കണം',
    pleaseValidEMail: 'ദയവായി ഒരു സാധുവായ ഇ-മെയിൽ നൽകുക',
    wesentOTP: 'നാം OTP അയച്ചു',
    ResendOTP: 'OTP വീണ്ടും അയയ്‌ക്കുക',
    Email: 'ഇ-മെയിൽ',
    Password: 'പാസ്വേഡ്',
    loginwithotp: 'OTP ഉപയോഗിച്ച് ലോഗിൻ ചെയ്യുക',
    loginwithpass: 'പാസ്വേഡ് ഉപയോഗിച്ച് ലോഗിൻ ചെയ്യുക',
    loginwithwhatsapp: 'വാട്ട്സ്ആപ്പ് ഉപയോഗിച്ച് ലോഗിൻ ചെയ്യുക',
    loginwithmobile: 'ഇ-മെയിൽ ഉപയോഗിച്ച് ലോഗിൻ ചെയ്യുക',
    verifyEmail: 'നിങ്ങളുടെ ഇ-മെയിൽ സ്ഥിരീകരിക്കുക',
    addPhoneNumber:
      'നിങ്ങളുടെ ഇ-മെയിൽ ചേർക്കുക. ഞങ്ങൾ നിങ്ങൾക്ക് ഒരു സ്ഥിരീകരണ കോഡ് അയക്കാം.',
    enterPassword:
      'ആപ്പ് പ്രവേശിക്കാൻ നിങ്ങളുടെ രജിസ്റ്റർ ചെയ്ത മൊബൈൽ നമ്പറും പാസ്വേഡും നൽകുക.',
    login: 'ലോഗിൻ',
    sendotp: 'OTP അയക്കുക',
    Profile: 'പ്രൊഫൈൽ',
    Premium: 'പ്രിമിയം',
    myProfile: 'എന്റെ പ്രൊഫൈൽ',
    ProductsPlans: 'ഉത്പന്നങ്ങളും പദ്ധതികളും',
    MyOrder: 'എന്റെ ഓർഡർ',
    changeLanguage: 'ഭാഷ മാറ്റുക',
    PrivacyPolicy: 'ഗോപനതാ നയം',
    TermsCondition: 'നിബന്ധനകൾ',
    Subscription: 'സബ്സ്ക്രിപ്ഷൻ T&C',
    Logout: 'ലോഗ് ഔട്ട് അക്കൗണ്ട്',
    Goodnoon: 'ശുഭ കാലാവധി',
    Goodmorning: 'ശുഭോദയം',
    Goodevening: 'ശുഭ സന്ധ്യ',
    yourChild:
      'നിങ്ങളുടെ കുട്ടിക്കുള്ള ഏറ്റവും മികച്ച നിക്ഷേപം, നിങ്ങളുടെ ഭാവി',
    setting: 'സജ്ജീകരണങ്ങൾ',
    signup: 'സൈൻ അപ്പ്',
    fullname: 'പൂർണ്ണ പേര്',
    enterYourFullname: 'നിങ്ങളുടെ പൂർണ്ണ പേര് നൽകുക',
    userMo: 'മൊബൈൽ നമ്പർ',
    enterusermo: 'നിങ്ങളുടെ മൊബൈൽ നമ്പർ നൽകുക',
    chooseyourePreferred: 'നിങ്ങളുടെ ഇഷ്ടഭാഷ തിരഞ്ഞെടുക്കുക',
    chooseLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    bestinvestement: 'നിന്റെ ഭാവിക്കായി ഏറ്റവും മികച്ച നിക്ഷേപം',
    yourchild: 'നിന്റെ കുട്ടി, നിന്റെ ഭാവി',
    gold: 'പവാന്',
    silver: 'ചിങ്ങല',
    platinum: 'പ്ലാറ്റിനം',
    off: 'ഓഫ്',
    premiumtitletxt:
      'ഹിരണ്യഗർഭ പുസ്തകം നേടുക, ഗർഭിണി കുട്ടികളുടെ PQ, IQ, EQ, & SQ വികസനത്തിന് 25+ ദിനംപ്രതി പ്രവർത്തനങ്ങൾ',
    helpno: 'ഹെൽപ്ലൈൻ നമ്പർ : ',
    pay: 'പേ',
    LMP: 'നിന്റെ അവസാന മാസികാന്തമായ കാലയളവ് രേഖപ്പെടുത്തുക',
    EDD: 'നിന്റെ പ്രതീക്ഷിക്കുന്ന ജനനതീയതി രേഖപ്പെടുത്തുക',
  },
  mr: {
    welcome: 'स्वागत आहे',
    welcometoh: 'हिरण्यगर्भा मध्ये आपले स्वागत आहे',
    subText: 'भारताची सर्वात विश्वासार्ह \nऑनलाइन गर्भसंस्कार समुदाय',
    changeLanguage: 'भाषा बदला',
    Hi: 'नमस्कार',
    howCanHelp: 'आपल्याला कसे मदत करू शकतो?',
    chatWithUs: 'आमच्याशी चॅट करा',
    support: 'सपोर्ट',
    enterYourEmail: 'तुमचा ईमेल प्रविष्ट करा',
    enterYourPass: 'तुमचा पासवर्ड प्रविष्ट करा',
    password6Digit: 'पासवर्ड किमान ६ अंकी असावा',
    pleaseValidEMail: 'कृपया वैध ईमेल प्रविष्ट करा',
    wesentOTP: 'आम्ही OTP पाठवला आहे',
    ResendOTP: 'OTP पुन्हा पाठवा',
    Email: 'ईमेल',
    Password: 'पासवर्ड',
    loginwithotp: 'OTP ने लॉगिन करा',
    loginwithpass: 'पासवर्ड ने लॉगिन करा',
    loginwithwhatsapp: 'व्हॉट्सअॅप ने लॉगिन करा',
    loginwithmobile: 'ईमेल ने लॉगिन करा',
    verifyEmail: 'तुमचा ईमेल सत्यापित करा',
    addPhoneNumber: 'तुमचा ईमेल जोडा. आम्ही एक सत्यापन कोड पाठवू.',
    enterPassword:
      'आँप मध्ये प्रवेश करण्यासाठी तुमचा नोंदणीकृत मोबाइल नंबर आणि पासवर्ड प्रविष्ट करा.',
    login: 'लॉगिन',
    sendotp: 'OTP पाठवा',
    Profile: 'प्रोफाइल',
    Premium: 'प्रीमियम',
    myProfile: 'माझा प्रोफाइल',
    ProductsPlans: 'उत्पादन आणि योजना',
    MyOrder: 'माझा ऑर्डर',
    changeLanguage: 'भाषा बदला',
    PrivacyPolicy: 'गोपनीयता धोरण',
    TermsCondition: 'अटी आणि शर्ती',
    Subscription: 'सदस्यता अटी',
    Logout: 'लॉगआउट करा',
    Goodnoon: 'गुड आफ्टरनून',
    Goodmorning: 'गुड मॉर्निंग',
    Goodevening: 'गुड इव्हिनिंग',
    yourChild: 'तुमच्या मुलासाठी, तुमच्या भविष्यसाठी सर्वोत्तम गुंतवणूक',
    setting: 'सेटिंग',
    signup: 'साइन अप करा',
    fullname: 'पूर्ण नाव',
    enterYourFullname: 'तुमचं पूर्ण नाव प्रविष्ट करा',
    userMo: 'मोबाइल नंबर',
    enterusermo: 'तुमचा मोबाइल नंबर प्रविष्ट करा',
    chooseyourePreferred: 'तुमची पसंतीची भाषा निवडा',
    chooseLanguage: 'भाषा निवडा',
    bestinvestement: 'तुमच्यासाठी सर्वोत्तम गुंतवणूक',
    yourchild: 'तुमचं मूल, तुमचं भविष्य',
    gold: 'सोने',
    silver: 'चांदी',
    platinum: 'प्लॅटिनम',
    off: 'ऑफ',
    premiumtitletxt:
      'हिरण्यगर्भ पुस्तक मिळवा आणि गर्भवती मुलांच्या PQ, IQ, EQ आणि SQ विकासासाठी दररोज 25+ क्रियाकलाप',
    helpno: 'हेल्पलाइन नंबर : ',
    pay: 'पै',
    LMP: 'तुमच्या शेवटच्या मासिक पाळीचा कालावधी प्रविष्ट करा',
    EDD: 'तुमच्या अपेक्षित प्रसूत दिनांक प्रविष्ट करा',
  },
  mni: {
    welcome: 'ꯊꯦꯡꯅꯩ',
    welcometoh: 'ꯀꯨꯝꯖꯕ ꯏꯝꯅꯛ ꯈꯣꯛꯇ ꯍꯩꯁꯦ',
    subText: 'ꯏꯋꯦ ꯇꯔꯥꯏ ꯅꯩꯉ ꯏꯃꯅꯦꯝ \nꯍꯩꯂꯥꯛ ꯆꯦꯚꯥ ꯆꯥꯀꯡꯤꯕꯕ',
    changeLanguage: 'ꯗꯦꯡꯅꯩ ꯍꯝꯁꯦ',
    Hi: 'ꯀꯧ',
    howCanHelp: 'ꯆꯦꯡꯒꯤꯁꯦ ꯍꯧꯃ꯭?',
    chatWithUs: 'ꯑꯦꯝꯝꯏ ꯇꯩꯋ',
    support: 'ꯁꯦꯜꯅ',
    enterYourEmail: 'ꯑꯧꯟꯛ ꯋꯥꯝꯔꯤꯠ',
    enterYourPass: 'ꯑꯧꯟꯛ ꯍꯥꯝꯣꯛ',
    password6Digit: 'ꯍꯥꯝꯣꯛ 6 ꯛꯁꯧ',
    pleaseValidEMail: 'ꯍꯥꯁꯦꯟ ꯁꯧꯇꯣꯅꯟ  ꯋꯥꯝꯔꯤꯠ',
    wesentOTP: 'ꯈꯥꯛꯚ ꯇꯅꯗ ꯀꯇ ꯊꯦ OTP',
    ResendOTP: 'OTP ꯄꯦꯖꯣꯛ',
    Email: 'ꯋꯥꯝꯔꯤꯠ',
    Password: 'ꯍꯥꯝꯣꯛ',
    loginwithotp: 'OTP ꯄꯦꯔ ꯍꯩꯂꯥ',
    loginwithpass: 'ꯍꯥꯝꯣꯛ ꯄꯦꯔ ꯍꯩꯂꯥ',
    loginwithwhatsapp: 'व्हॉट्सअॅप ꯄꯦꯔ ꯍꯩꯂꯥ',
    loginwithmobile: 'ꯑꯧꯟꯛ ꯋꯥꯝꯔꯤꯠ ꯄꯦꯔ ꯍꯩꯂꯥ',
    verifyEmail: 'ꯑꯧꯟꯛ ꯋꯥꯝꯔꯤꯠ ꯍꯦꯠꯟꯇ',
    addPhoneNumber: 'ꯑꯧꯟꯛ ꯋꯥꯝꯔꯤꯠ  ꯈꯅꯦꯢꯇꯒꯤ, ꯄꯦꯔ ꯐꯠꯖꯣꯛꯠ',
    enterPassword: 'ꯑꯧꯟꯛ ꯍꯥꯝꯣꯛ ꯇꯅꯗ ꯍꯥꯝꯣꯛ ꯀꯍꯧꯝ',
    login: 'ꯍꯦꯅꯔ',
    sendotp: 'OTP ꯇꯨꯛ',
    Profile: 'ꯍꯩꯂꯥꯛ',
    Premium: 'ꯄꯦꯔꯦꯍ',
    myProfile: 'ꯌꯩꯂꯥꯛ',
    ProductsPlans: 'ꯑꯦꯛꯡ ꯏꯃꯅꯦꯝ',
    MyOrder: 'ꯌꯥꯠꯇ',
    changeLanguage: 'ꯗꯦꯡꯅꯩ ꯍꯝꯁꯦ',
    PrivacyPolicy: 'ꯁꯤꯙꯤꯡ ꯇꯦꯝꯁ',
    TermsCondition: 'ꯇꯦꯝꯁꯦ ꯆꯦꯡꯕꯦ',
    Subscription: 'ꯄꯦꯖꯥ ꯇꯦꯝꯁ',
    Logout: 'ꯍꯦꯅꯔ ꯑꯡꯀꯣꯡ',
    Goodnoon: 'ꯇꯦꯡꯧ ꯆꯦꯝꯦ',
    Goodmorning: 'ꯇꯦꯡꯧ ꯍꯦꯟꯦ',
    Goodevening: 'ꯇꯦꯡꯧ ꯗꯥꯡ',
    yourChild: 'ꯈꯥꯛꯚ ꯏꯋꯦ ꯇꯦꯡꯧ ꯀꯥꯛꯁꯩꯡꯀꯥ ꯗꯦꯡꯧ',
    setting: 'ꯁꯦꯕꯩ',
    signup: 'ꯁꯦꯡ ꯏꯕ',
    fullname: 'ꯇꯧꯇ ꯅꯥꯡ',
    enterYourFullname: 'ꯑꯧꯟꯛ ꯇꯧꯇ ꯅꯥꯡ',
    userMo: 'ꯅꯥꯡ ꯏꯁ',
    enterusermo: 'ꯑꯧꯟꯛ ꯅꯥꯡ ꯏꯁ',
    chooseyourePreferred: 'ꯄꯦꯡ ꯇꯦꯡꯧ ꯍꯥꯝꯁꯦ ꯅꯩꯉ',
    chooseLanguage: 'ꯄꯦꯡ ꯍꯦꯝꯁꯦ',
    bestinvestement: 'আপুনাৰ বাবে আট্টুং থকচি বিনিয়োগ',
    yourchild: 'আপুনাৰ শিশু, আপুনাৰ ভবিষ্যত',
    gold: 'ꯁꯣꯅꯥ',
    silver: 'ꯃꯥꯌꯤ',
    platinum: 'ପ୍ଲାଟିନମ୍',
    off: 'অফ',
    premiumtitletxt:
      'Hiranyagarbha Book puthaba le 25+ thajaba karik adu Unborn Childs PQ, IQ, EQ, leh SQ khangba',
    helpno: 'হেল্পলাইন নম্বর : ',
    pay: 'পে',
    LMP: 'আপনার শেষ মাসিক ঋতু দিন লিখুন',
    EDD: 'আপনার প্রত্যাশিত প্রসব তারিখ লিখুন',
  },
  lus: {
    welcome: 'Chibai',
    welcometoh: 'HiranyaGarbha hi chibai',
    subText: 'Indiak chuan hmingchhiatna \nOnline Garbhsanskar Community',
    changeLanguage: 'Chhinchhiahna a chiang',
    Hi: 'Hih',
    howCanHelp: 'Iva ang hian a hmuang chhuak?',
    chatWithUs: 'Kan thupui tawh',
    support: 'Tualchhiat',
    enterYourEmail: 'I Email tarlan',
    enterYourPass: 'I Password tarlan',
    password6Digit: 'Password a 6 ding an ni',
    pleaseValidEMail: 'Email a tarlan chhuak',
    wesentOTP: 'OTP chu kan i hmuak a, kan i hmuak a',
    ResendOTP: 'OTP chhuak angin',
    Email: 'Email',
    Password: 'Password',
    loginwithotp: 'OTP chhuak tawh',
    loginwithpass: 'Password chhuak tawh',
    loginwithwhatsapp: 'WhatsApp chhuak tawh',
    loginwithmobile: 'Email chhuak tawh',
    verifyEmail: 'I Email hmingchhiat',
    addPhoneNumber: 'I Email tarlan. A hnuaiah verification code kan chhuak a',
    enterPassword: 'App-ah hian password leh mobile number chhuak chhuak',
    login: 'Login',
    sendotp: 'OTP chhuak',
    Profile: 'Profile',
    Premium: 'Premium',
    myProfile: 'Kan Profile',
    ProductsPlans: 'Product leh Plans',
    MyOrder: 'Kan Order',
    changeLanguage: 'Chhinchhiahna a chiang',
    PrivacyPolicy: 'Hmingchhiatna chhinchhiahna',
    TermsCondition: 'Hmingchhiatna chhinchhiahna',
    Subscription: 'Subscription chhinchhiahna',
    Logout: 'Logout kan account',
    Goodnoon: 'Mingthang chhiat',
    Goodmorning: 'Mingthang chhuak',
    Goodevening: 'Nawmthang chhiat',
    yourChild: 'I ngaihnawm zawk a nihna kan mihring, kan thianghlim',
    setting: 'Settings',
    signup: 'Sign Up',
    fullname: 'Hming leh an lang',
    enterYourFullname: 'I hming leh an lang tarlan',
    userMo: 'Mobile No.',
    enterusermo: 'I mobile no tarlan',
    chooseyourePreferred: 'I hmingchhiatna a chiang chhuak',
    chooseLanguage: 'Chhinchhiahna a chiang',
    bestinvestement: 'I thu chhuak hle tih zawng a ni',
    yourchild: 'I hming chhuak, I thlir chhuak',
    gold: 'Zoh',
    silver: 'Chhandi',
    platinum: 'Platinum',
    off: 'off',
    premiumtitletxt:
      'Hiranyagarbha Book a chhut a, a hmingthang 25+ a hman a, Unborn Childs PQ, IQ, EQ, leh SQ a hman chuang a',
    helpno: 'ହେଲ୍ପଲାଇନ ନମ୍ବର : ',
    pay: 'ପେ',
    LMP: 'Chul thil nawnna a hmingthang zawng lo',
    EDD: 'Thilna chhuakna ziakna chungchang a hmingthang zawng lo',
  },
  or: {
    welcome: 'ସ୍ବାଗତ',
    welcometoh: 'ହିରଣ୍ୟଗର୍ଭକୁ ସ୍ବାଗତ',
    subText: 'ଭାରତର ସବୁଠାରୁ ବିଶ୍ବସନୀୟ \nଅନଲାଇନ୍ ଗର୍ଭସଂସ୍କାର କମ୍ୟୁନିଟି',
    changeLanguage: 'ଭାଷା ବଦଳାନ୍ତୁ',
    Hi: 'ନମସ୍କାର',
    howCanHelp: 'ଆମେ କିପରି ସହାୟତା କରିପାରିବା?',
    chatWithUs: 'ଆମ ସହିତ ଚାଟ୍ କରନ୍ତୁ',
    support: 'ସହାୟତା',
    enterYourEmail: 'ଆପଣଙ୍କର ଇମେଲ୍ ରାଖନ୍ତୁ',
    enterYourPass: 'ଆପଣଙ୍କର ପାସ୍‌ୱାର୍ଡ ରାଖନ୍ତୁ',
    password6Digit: 'ପାସ୍‌ୱାର୍ଡରେ 6 ଟି ଚରିତ୍ର ହେବା ଦରକାର',
    pleaseValidEMail: 'ଦୟାକରି ଏକ ବେଧାନୀୟ ଇମେଲ୍ ପ୍ରବେଶ କରନ୍ତୁ',
    wesentOTP: 'ଆମେ OTP ପଠାଇଛୁ',
    ResendOTP: 'OTP ପୁନଃ ପଠାନ୍ତୁ',
    Email: 'ଇମେଲ୍',
    Password: 'ପାସ୍‌ୱାର୍ଡ',
    loginwithotp: 'OTP ସହିତ ଲଗଇନ୍',
    loginwithpass: 'ପାସ୍‌ୱାର୍ଡ ସହିତ ଲଗଇନ୍',
    loginwithwhatsapp: 'ୱାଟସ୍‌ଆପ୍ ସହିତ ଲଗଇନ୍',
    loginwithmobile: 'ଇମେଲ୍ ସହିତ ଲଗଇନ୍',
    verifyEmail: 'ଆପଣଙ୍କର ଇମେଲ୍ ସଂପରିକ୍ଷଣ କରନ୍ତୁ',
    addPhoneNumber:
      'ଆପଣଙ୍କର ଇମେଲ୍ ଯୋଗ କରନ୍ତୁ। ଆମେ ଆପଣଙ୍କୁ ଏକ ସଂପରିକ୍ଷଣ କୋଡ୍ ପଠାଇବା',
    enterPassword:
      'ଆପଣଙ୍କର ରେଜିଷ୍ଟର୍ ମୋବାଇଲ୍ ନମ୍ବର ଓ ପାସ୍‌ୱାର୍ଡ ଦ୍ୱାରା ଆପ୍ଲିକେସନ୍ କୁ ଆକ୍ସେସ୍ କରନ୍ତୁ',
    login: 'ଲଗଇନ୍',
    sendotp: 'OTP ପଠାନ୍ତୁ',
    Profile: 'ପ୍ରୋଫାଇଲ୍',
    Premium: 'ପ୍ରିମିୟମ୍',
    myProfile: 'ମୋର ପ୍ରୋଫାଇଲ୍',
    ProductsPlans: 'ପ୍ରଡକ୍ଟ୍ ଏବଂ ପ୍ଲାନ୍ସ',
    MyOrder: 'ମୋର ଆର୍ଡର୍',
    changeLanguage: 'ଭାଷା ବଦଳାନ୍ତୁ',
    PrivacyPolicy: 'ଗୋପନୀୟତା ନୀତି',
    TermsCondition: 'ଟର୍ମସ୍ ଏବଂ କଣ୍ଡିସନ୍',
    Subscription: 'ସବ୍ସ୍କ୍ରିପ୍ସନ୍ ଟି ଏଣ୍ଡ୍ ସି',
    Logout: 'ଲଗଆଉଟ୍ ଆକାଉଣ୍ଟ୍',
    Goodnoon: 'ସୁଖଦ ବାସନ୍ଦ',
    Goodmorning: 'ସୁପ୍ରଭାତ',
    Goodevening: 'ସୁଖଦ ସଂଧ୍ୟା',
    yourChild: 'ଆପଣଙ୍କର ସିଶୁ ପାଇଁ ସର୍ବୋତ୍ତମ ନିବେଶ, ଆପଣଙ୍କର ଭବିଷ୍ୟତ୍',
    setting: 'ସେଟିଂ',
    signup: 'ସାଇନ୍ ଅପ୍',
    fullname: 'ପୂର୍ଣ୍ଣ ନାମ',
    enterYourFullname: 'ଆପଣଙ୍କର ପୂର୍ଣ୍ଣ ନାମ ଲେଖନ୍ତୁ',
    userMo: 'ମୋବାଇଲ୍ ନମ୍ବର୍',
    enterusermo: 'ଆପଣଙ୍କର ମୋବାଇଲ୍ ନମ୍ବର୍ ଲେଖନ୍ତୁ',
    chooseyourePreferred: 'ଆପଣଙ୍କର ପ୍ରିଫର୍ଡ ଭାଷା ଚୟନ କରନ୍ତୁ',
    chooseLanguage: 'ଭାଷା ଚୟନ କରନ୍ତୁ',
    bestinvestement: 'ଆପଣଙ୍କ ପାଇଁ ସର୍ବୋତ୍ତମ ନିବେଶ',
    yourchild: 'ଆପଣଙ୍କ ଶିଶୁ, ଆପଣଙ୍କ ଭବିଷ୍ୟତ',
    gold: 'ସୋନା',
    silver: 'ଚାନ୍ଦି',
    platinum: 'ପ୍ଲାଟିନମ୍',
    off: 'ଅଫ୍',
    premiumtitletxt:
      'ହିରଣ୍ୟଗର୍ଭା ପୁସ୍ତକ ପାଇଁ  ଓ  ଗର୍ଭରେ ଥିବା ଶିଶୁଙ୍କ ପାଇଁ PQ, IQ, EQ, ଏବଂ SQ ଉନ୍ନତିକୁ ସହଯୋଗ କରିବା ପାଇଁ 25+ ଦୈନିକ କ୍ରିୟା',
    helpno: 'ਹੈਲਪਲਾਈਨ ਨੰਬਰ : ',
    pay: 'ਪੇ',
    LMP: 'ଆପଣଙ୍କର ଶେଷ ମାସିକ ଅବଧି ଲେଖନ୍ତୁ',
    EDD: 'ଆପଣଙ୍କର ଆଶା କିୱେଁ ଜନ୍ମ ତାରିଖ ଲେଖନ୍ତୁ',
  },
  pa: {
    welcome: 'ਸਵਾਗਤ ਹੈ',
    welcometoh: 'ਹਿਰਣ੍ਯਗਰਭ ਵਿੱਚ ਸਵਾਗਤ ਹੈ',
    subText: 'ਭਾਰਤ ਦਾ ਸਭ ਤੋਂ ਭਰੋਸੇਯੋਗ \nਆਨਲਾਈਨ ਗਰਭਸੰਸਕਾਰ ਕਮਿਊਨਿਟੀ',
    changeLanguage: 'ਭਾਸ਼ਾ ਬਦਲੋ',
    Hi: 'ਹੈਲੋ',
    howCanHelp: 'ਅਸੀਂ ਤੁਹਾਡੀ ਕਿਵੇਂ ਮਦਦ ਕਰ ਸਕਦੇ ਹਾਂ?',
    chatWithUs: 'ਸਾਡੇ ਨਾਲ ਗੱਲ ਕਰੋ',
    support: 'ਸਹਾਇਤਾ',
    enterYourEmail: 'ਆਪਣਾ ਈ-ਮੇਲ ਦਾਖਲ ਕਰੋ',
    enterYourPass: 'ਆਪਣਾ ਪਾਸਵਰਡ ਦਾਖਲ ਕਰੋ',
    password6Digit: 'ਪਾਸਵਰਡ ਘੱਟੋ ਘੱਟ 6 ਅੰਕਾਂ ਦਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ',
    pleaseValidEMail: 'ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਮਾਨਯੋਗ ਈ-ਮੇਲ ਦਾਖਲ ਕਰੋ',
    wesentOTP: 'ਅਸੀਂ OTP ਭੇਜ ਦਿੱਤਾ ਹੈ',
    ResendOTP: 'OTP ਦੁਬਾਰਾ ਭੇਜੋ',
    Email: 'ਈ-ਮੇਲ',
    Password: 'ਪਾਸਵਰਡ',
    loginwithotp: 'OTP ਨਾਲ ਲੌਗਇਨ ਕਰੋ',
    loginwithpass: 'ਪਾਸਵਰਡ ਨਾਲ ਲੌਗਇਨ ਕਰੋ',
    loginwithwhatsapp: 'ਵਟਸਐਪ ਨਾਲ ਲੌਗਇਨ ਕਰੋ',
    loginwithmobile: 'ਈ-ਮੇਲ ਨਾਲ ਲੌਗਇਨ ਕਰੋ',
    verifyEmail: 'ਆਪਣੀ ਈ-ਮੇਲ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
    addPhoneNumber:
      'ਆਪਣੀ ਈ-ਮੇਲ ਦਾਖਲ ਕਰੋ। ਅਸੀਂ ਤੁਹਾਨੂੰ ਇੱਕ ਪ੍ਰਮਾਣੀਕਰਨ ਕੋਡ ਭੇਜਾਂਗੇ',
    enterPassword:
      'ਐਪਸ ਵਿੱਚ ਪ੍ਰਵੇਸ਼ ਕਰਨ ਲਈ ਆਪਣਾ ਰਜਿਸਟਰਡ ਮੋਬਾਈਲ ਨੰਬਰ ਅਤੇ ਪਾਸਵਰਡ ਦਾਖਲ ਕਰੋ',
    login: 'ਲੌਗਇਨ',
    sendotp: 'OTP ਭੇਜੋ',
    Profile: 'ਪ੍ਰੋਫਾਈਲ',
    Premium: 'ਪ੍ਰੀਮੀਅਮ',
    myProfile: 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ',
    ProductsPlans: 'ਉਤਪਾਦ ਅਤੇ ਯੋਜਨਾਵਾਂ',
    MyOrder: 'ਮੇਰਾ ਆਰਡਰ',
    changeLanguage: 'ਭਾਸ਼ਾ ਬਦਲੋ',
    PrivacyPolicy: 'ਗੋਪਨੀਯਤਾ ਨੀਤੀ',
    TermsCondition: 'ਸ਼ਰਤਾਂ ਅਤੇ ਨਿਯਮ',
    Subscription: 'ਸਬਸਕ੍ਰਿਪਸ਼ਨ ਟੀਐਂਸੀ',
    Logout: 'ਅਕਾਊਂਟ ਲੌਗਆਉਟ ਕਰੋ',
    Goodnoon: 'ਦੁਪਹਿਰ ਦੀਆਂ ਸ਼ੁਭਕਾਮਨਾਵਾਂ',
    Goodmorning: 'ਸੁਪ੍ਰਭਾਤ',
    Goodevening: 'ਸ਼ਾਮ ਦੀਆਂ ਸ਼ੁਭਕਾਮਨਾਵਾਂ',
    yourChild: 'ਤੁਹਾਡੇ ਬੱਚੇ ਲਈ ਸਭ ਤੋਂ ਵਧੀਆ ਨਿਵੇਸ਼, ਤੁਹਾਡਾ ਭਵਿੱਖ',
    setting: 'ਸੈਟਿੰਗ',
    signup: 'ਸਾਈਨ ਅੱਪ',
    fullname: 'ਪੂਰਾ ਨਾਮ',
    enterYourFullname: 'ਆਪਣਾ ਪੂਰਾ ਨਾਮ ਦਾਖਲ ਕਰੋ',
    userMo: 'ਮੋਬਾਈਲ ਨੰਬਰ',
    enterusermo: 'ਆਪਣਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਾਖਲ ਕਰੋ',
    chooseyourePreferred: 'ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ',
    chooseLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    bestinvestement: 'ਤੁਹਾਡੇ ਲਈ ਸਭ ਤੋਂ ਵਧੀਆ ਨਿਵੇਸ਼',
    yourchild: 'ਤੁਹਾਡਾ ਬੱਚਾ, ਤੁਹਾਡਾ ਭਵਿੱਖ',
    gold: 'ਸੋਨਾ',
    silver: 'ਚਾਂਦੀ',
    platinum: 'ਪਲੈਟਿਨਮ',
    off: 'ਆਫ਼',
    premiumtitletxt:
      'ਹਿਰਣ੍ਯਗਰਭ ਕਿਤਾਬ ਪ੍ਰਾਪਤ ਕਰੋ ਅਤੇ ਗਰਭਵਤੀ ਬੱਚਿਆਂ ਦੇ PQ, IQ, EQ ਅਤੇ SQ ਵਿਕਾਸ ਲਈ ਦਿਨ ਵਿਚ 25+ ਕਿਰਿਆਵਾਂ',
    helpno: 'ਹੈਲਪਲਾਈਨ ਨੰਬਰ : ',
    pay: 'ਪੇ',
    LMP: 'ਆਪਣੇ ਆਖਰੀ ਮਹਾਵਾਰੀ ਦਾ ਸਮਾਂ ਦਰਜ ਕਰੋ',
    EDD: 'ਆਪਣੀ ਉਮੀਦ ਕੀਤੀ ਜਨਮ ਦੀ ਤਾਰੀਖ ਦਰਜ ਕਰੋ',
  },
  ta: {
    welcome: 'வாங்கம்',
    welcometoh: 'ஹிரண்யகர்பத்தில் வரவேற்கின்றேன்',
    subText:
      'இந்தியாவின் மிகுந்த நம்பிக்கைக்குரிய \nஆன்லைன் கர்ப்சன்ஸ்கார் சமூகம்',
    changeLanguage: 'மொழி மாற்று',
    Hi: 'ஹாய்',
    howCanHelp: 'நாங்கள் உங்களுக்கு எப்படி உதவ முடியும்?',
    chatWithUs: 'நமக்கு பேசவும்',
    support: 'ஆதரவு',
    enterYourEmail: 'உங்கள் ஈ-மெயில் ஐ உள்ளிடவும்',
    enterYourPass: 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    password6Digit:
      'கடவுச்சொல் குறைந்தது 6 எழுத்துகள் உள்ளனவாக இருக்க வேண்டும்',
    pleaseValidEMail: 'ஒரு செல்லுபடியாகும் ஈ-மெயிலை உள்ளிடவும்',
    wesentOTP: 'நாங்கள் OTP ஐ அனுப்பினோம்',
    ResendOTP: 'OTP ஐ மீண்டும் அனுப்பவும்',
    Email: 'ஈ-மெயில்',
    Password: 'கடவுச்சொல்',
    loginwithotp: 'OTP உடன் உள்நுழைகவும்',
    loginwithpass: 'கடவுச்சொல்லுடன் உள்நுழைகவும்',
    loginwithwhatsapp: 'வாட்ஸ்அப் உடன் உள்நுழைகவும்',
    loginwithmobile: 'ஈ-மெயிலுடன் உள்நுழைகவும்',
    verifyEmail: 'உங்கள் ஈ-மெயிலை சரிபார்க்கவும்',
    addPhoneNumber:
      'உங்கள் ஈ-மெயிலை உள்ளிடவும். நாம் உங்களுக்கு ஒரு சரிபார்ப்பு குறியீட்டை அனுப்புவோம்',
    enterPassword:
      'பயன்பாட்டில் அணுகுவதற்கு உங்கள் பதிவு செய்யப்பட்ட மொபைல் எண் மற்றும் கடவுச்சொல்லை உள்ளிடவும்',
    login: 'உள்நுழை',
    sendotp: 'OTP அனுப்பவும்',
    Profile: 'சுயவிவரம்',
    Premium: 'பிரீமியம்',
    myProfile: 'என் சுயவிவரம்',
    ProductsPlans: 'உதயங்கள் மற்றும் திட்டங்கள்',
    MyOrder: 'என் ஆர்டர்',
    changeLanguage: 'மொழி மாற்று',
    PrivacyPolicy: 'பதிவுகள் கொள்கை',
    TermsCondition: 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
    Subscription: 'சந்தா நிபந்தனைகள்',
    Logout: 'வெளியீடு கணக்கு',
    Goodnoon: 'பிற்பகல் வாழ்த்துக்கள்',
    Goodmorning: 'காலை வணக்கம்',
    Goodevening: 'மாலை வணக்கம்',
    yourChild:
      'உங்கள் குழந்தைக்கு செய்யக்கூடிய சிறந்த முதலீடு, உங்கள் எதிர்காலம்',
    setting: 'அமைப்புகள்',
    signup: 'பதிவுசெய்யவும்',
    fullname: 'முழு பெயர்',
    enterYourFullname: 'உங்கள் முழு பெயரை உள்ளிடவும்',
    userMo: 'மொபைல் எண்',
    enterusermo: 'உங்கள் மொபைல் எண் உள்ளிடவும்',
    chooseyourePreferred: 'உங்கள் விருப்பமான மொழியை தேர்வு செய்யவும்',
    chooseLanguage: 'மொழி தேர்வு செய்யவும்',
    bestinvestement: 'உங்களுக்கான சிறந்த முதலீடு',
    yourchild: 'உங்கள் பிள்ளை, உங்கள் எதிர்காலம்',
    gold: 'பொன்',
    silver: 'வெள்ளி',
    platinum: 'பிளாட்டினம்',
    off: 'ஆப்',
    premiumtitletxt:
      'ஹிரண்யகர்ப புத்தகத்தை பெறவும் மற்றும் கர்ப்பிணி குழந்தைகளுக்கான PQ, IQ, EQ மற்றும் SQ வளர்ச்சிக்காக நாளை 25+ செயல்பாடுகள்',
    helpno: 'ஹெல்ப்லைன் எண் : ',
    pay: 'பே',
    LMP: 'உங்கள் கடைசியாக வந்த மாதவிடாய் காலத்தை எடுத்து பதிவு செய்யவும்',
    EDD: 'உங்கள் எதிர்பார்க்கப்பட்ட பிறப்பு தேதியை பதிவு செய்யவும்',
  },
  ur: {
    welcome: 'خوش آمدید',
    welcometoh: 'ہیرنیاگربھا میں خوش آمدید',
    subText: 'بھارت کا سب سے زیادہ قابل اعتماد \nآن لائن گربھسنسکار کمیونٹی',
    changeLanguage: 'زبان تبدیل کریں',
    Hi: 'ہیلو',
    howCanHelp: 'ہم آپ کی کس طرح مدد کر سکتے ہیں؟',
    chatWithUs: 'ہمارے ساتھ بات کریں',
    support: 'مدد',
    enterYourEmail: 'اپنا ای میل درج کریں',
    enterYourPass: 'اپنا پاس ورڈ درج کریں',
    password6Digit: 'پاس ورڈ کم از کم 6 حروف پر مشتمل ہونا چاہیے',
    pleaseValidEMail: 'براہ کرم ایک درست ای میل درج کریں',
    wesentOTP: 'ہم نے OTP بھیجا ہے',
    ResendOTP: 'OTP دوبارہ بھیجیں',
    Email: 'ای میل',
    Password: 'پاس ورڈ',
    loginwithotp: 'OTP کے ساتھ لاگ ان کریں',
    loginwithpass: 'پاس ورڈ کے ساتھ لاگ ان کریں',
    loginwithwhatsapp: 'واٹس ایپ کے ساتھ لاگ ان کریں',
    loginwithmobile: 'ای میل کے ساتھ لاگ ان کریں',
    verifyEmail: 'اپنی ای میل کی تصدیق کریں',
    addPhoneNumber: 'اپنی ای میل درج کریں۔ ہم آپ کو ایک تصدیقی کوڈ بھیجیں گے',
    enterPassword:
      'ایپ تک رسائی حاصل کرنے کے لیے اپنا رجسٹرڈ موبائل نمبر اور پاس ورڈ درج کریں',
    login: 'لاگ ان کریں',
    sendotp: 'OTP بھیجیں',
    Profile: 'پروفائل',
    Premium: 'پریمیئم',
    myProfile: 'میری پروفائل',
    ProductsPlans: 'مصنوعات اور منصوبے',
    MyOrder: 'میرا آرڈر',
    changeLanguage: 'زبان تبدیل کریں',
    PrivacyPolicy: 'پرائیویسی پالیسی',
    TermsCondition: 'شرائط و ضوابط',
    Subscription: 'سبسکرپشن کی شرائط',
    Logout: 'اکاؤنٹ سے لاگ آؤٹ کریں',
    Goodnoon: 'دوپہر بخیر',
    Goodmorning: 'صبح بخیر',
    Goodevening: 'شام بخیر',
    yourChild: 'آپ کی بچے کے لئے سب سے بہترین سرمایہ کاری، آپ کا مستقبل',
    setting: 'سیٹنگ',
    signup: 'سائن اپ کریں',
    fullname: 'مکمل نام',
    enterYourFullname: 'اپنا مکمل نام درج کریں',
    userMo: 'موبائل نمبر',
    enterusermo: 'اپنا موبائل نمبر درج کریں',
    chooseyourePreferred: 'اپنی پسندیدہ زبان منتخب کریں',
    chooseLanguage: 'زبان منتخب کریں',
    bestinvestement: 'آپ کے لیے بہترین سرمایہ کاری',
    yourchild: 'آپ کا بچہ، آپ کا مستقبل',
    gold: 'سونا',
    silver: 'چاندی',
    platinum: 'پلاٹینم',
    off: 'آف',
    premiumtitletxt:
      'ہیرنیاگربھا کتاب حاصل کریں اور حمل کے بچوں کے PQ، IQ، EQ، اور SQ کی ترقی کے لئے روزانہ 25+ سرگرمیاں',
    helpno: 'ہیلپ لائن نمبر : ',
    pay: 'ادائیگی',
    LMP: 'اپنی آخری حیض کی تاریخ درج کریں',
    EDD: 'اپنی متوقع پیدائش کی تاریخ درج کریں',
  },
  bn: {
    welcome: 'স্বাগতম',
    welcometoh: 'হিরণ্যগর্ভে স্বাগতম',
    subText: 'ভারতের সবচেয়ে বিশ্বস্ত \nঅনলাইন গর্ভসঞ্চার সম্প্রদায়',
    changeLanguage: 'ভাষা পরিবর্তন করুন',
    Hi: 'হ্যালো',
    howCanHelp: 'আমরা আপনাকে কীভাবে সাহায্য করতে পারি?',
    chatWithUs: 'আমাদের সাথে চ্যাট করুন',
    support: 'সমর্থন',
    enterYourEmail: 'আপনার ইমেইল দিন',
    enterYourPass: 'আপনার পাসওয়ার্ড দিন',
    password6Digit: 'পাসওয়ার্ডটি কমপক্ষে 6 অক্ষরের হতে হবে',
    pleaseValidEMail: 'দয়া করে একটি বৈধ ইমেইল দিন',
    wesentOTP: 'আমরা OTP পাঠিয়েছি',
    ResendOTP: 'OTP আবার পাঠান',
    Email: 'ইমেইল',
    Password: 'পাসওয়ার্ড',
    loginwithotp: 'OTP দিয়ে লগইন করুন',
    loginwithpass: 'পাসওয়ার্ড দিয়ে লগইন করুন',
    loginwithwhatsapp: 'WhatsApp দিয়ে লগইন করুন',
    loginwithmobile: 'ইমেইল দিয়ে লগইন করুন',
    verifyEmail: 'আপনার ইমেইল যাচাই করুন',
    addPhoneNumber: 'আপনার ইমেইল দিন। আমরা আপনাকে একটি যাচাইকরণ কোড পাঠাবো',
    enterPassword:
      'অ্যাপে প্রবেশ করতে আপনার রেজিস্টার্ড মোবাইল নম্বর এবং পাসওয়ার্ড দিন',
    login: 'লগইন',
    sendotp: 'OTP পাঠান',
    Profile: 'প্রোফাইল',
    Premium: 'প্রিমিয়াম',
    myProfile: 'আমার প্রোফাইল',
    ProductsPlans: 'পণ্য ও পরিকল্পনা',
    MyOrder: 'আমার অর্ডার',
    changeLanguage: 'ভাষা পরিবর্তন করুন',
    PrivacyPolicy: 'গোপনীয়তা নীতি',
    TermsCondition: 'শর্তাবলী ও নীতি',
    Subscription: 'সাবস্ক্রিপশন শর্তাবলী',
    Logout: 'অ্যাকাউন্ট লগআউট করুন',
    Goodnoon: 'দুপুর বেলা শুভেচ্ছা',
    Goodmorning: 'শুভ সকাল',
    Goodevening: 'শুভ সন্ধ্যা',
    yourChild: 'আপনার শিশুর জন্য সেরা বিনিয়োগ, আপনার ভবিষ্যৎ',
    setting: 'সেটিং',
    signup: 'সাইন আপ করুন',
    fullname: 'পুরো নাম',
    enterYourFullname: 'আপনার পুরো নাম দিন',
    userMo: 'মোবাইল নম্বর',
    enterusermo: 'আপনার মোবাইল নম্বর দিন',
    chooseyourePreferred: 'আপনার পছন্দের ভাষা চয়ন করুন',
    chooseLanguage: 'ভাষা চয়ন করুন',
    bestinvestement: 'আপনার জন্য সেরা বিনিয়োগ',
    yourchild: 'আপনার শিশু, আপনার ভবিষ্যৎ',
    gold: 'সোনা',
    silver: 'রূপা',
    platinum: 'প্লাটিনাম',
    off: 'অফ',
    premiumtitletxt:
      'হিরণ্যগর্ভা বইটি পান এবং গর্ভবর্তী শিশুদের PQ, IQ, EQ, এবং SQ উন্নয়নের জন্য দৈনিক ২৫+ কার্যক্রম',
    helpno: 'হেল্পলাইন নম্বর : ',
    pay: 'পে',
    LMP: 'আপনার শেষ মাসিক ঋতু দিন লিখুন',
    EDD: 'আপনার প্রত্যাশিত প্রসব তারিখ লিখুন',
  },
  te: {
    welcome: 'స్వాగతం',
    welcometoh: 'హిరణ్యగర్భలో స్వాగతం',
    subText: 'భారతదేశంలో అత్యంత నమ్మకమైన \nఆన్‌లైన్ గర్భసంస్కార్ కమ్యూనిటీ',
    changeLanguage: 'భాష మార్చండి',
    Hi: 'హాయ్',
    howCanHelp: 'మేము మీకు ఎలా సహాయం చేయగలము?',
    chatWithUs: 'మాతో చాట్ చేయండి',
    support: 'మద్దతు',
    enterYourEmail: 'మీ ఇ-మెయిల్ నమోదు చేయండి',
    enterYourPass: 'మీ పాస్‌వర్డ్ నమోదు చేయండి',
    password6Digit: 'పాస్‌వర్డ్ కనీసం 6 అక్షరాలు ఉండాలి',
    pleaseValidEMail: 'దయచేసి ఒక సరైన ఇ-మెయిల్ నమోదు చేయండి',
    wesentOTP: 'మేము OTP ను పంపించాము',
    ResendOTP: 'OTP ను మళ్లీ పంపండి',
    Email: 'ఇ-మెయిల్',
    Password: 'పాస్‌వర్డ్',
    loginwithotp: 'OTP తో లాగిన్ అవ్వండి',
    loginwithpass: 'పాస్‌వర్డ్ తో లాగిన్ అవ్వండి',
    loginwithwhatsapp: 'వాట్సాప్ తో లాగిన్ అవ్వండి',
    loginwithmobile: 'ఇ-మెయిల్ తో లాగిన్ అవ్వండి',
    verifyEmail: 'మీ ఇ-మెయిల్‌ను ధృవీకరించండి',
    addPhoneNumber:
      'మీ ఇ-మెయిల్‌ను నమోదు చేయండి. మేము మీకు ధృవీకరణ కోడ్ పంపిస్తాము',
    enterPassword:
      'అప్లికేషన్‌కు యాక్సెస్ పొందడానికి మీ నమోదు చేసిన మొబైల్ నంబర్ మరియు పాస్‌వర్డ్ నమోదు చేయండి',
    login: 'లాగిన్',
    sendotp: 'OTP పంపండి',
    Profile: 'ప్రొఫైల్',
    Premium: 'ప్రీమియం',
    myProfile: 'నా ప్రొఫైల్',
    ProductsPlans: 'ఉత్పత్తులు & ప్రణాళికలు',
    MyOrder: 'నా ఆర్డర్',
    changeLanguage: 'భాష మార్చండి',
    PrivacyPolicy: 'గోప్యతా విధానం',
    TermsCondition: 'నియమాలు మరియు షరతులు',
    Subscription: 'సబ్స్క్రిప్షన్ షరతులు',
    Logout: 'అకౌంట్ నుండి లాగ్ఆౌట్ చేయండి',
    Goodnoon: 'మధ్యాహ్న వందనం',
    Goodmorning: 'శుభోదయం',
    Goodevening: 'శుభ సాయంత్రం',
    yourChild: 'మీ పిల్లల కోసం మీరు చేసే ఉత్తమ పెట్టుబడి, మీ భవిష్యత్',
    setting: 'సెట్టింగ్',
    signup: 'సైన్ అప్ చేయండి',
    fullname: 'పూర్తి పేరు',
    enterYourFullname: 'మీ పూర్తి పేరు నమోదు చేయండి',
    userMo: 'మొబైల్ నం.',
    enterusermo: 'మీ మొబైల్ నం. నమోదు చేయండి',
    chooseyourePreferred: 'మీ ఇష్టమైన భాషను ఎంచుకోండి',
    chooseLanguage: 'భాషను ఎంచుకోండి',
    bestinvestement: 'మీ కోసం ఉత్తమ పెట్టుబడి',
    yourchild: 'మీ పిల్లలు, మీ భవిష్యత్తు',
    gold: 'బంగారం',
    silver: 'వెంగిడి',
    platinum: 'ప్లాటినం',
    off: 'ఆఫ్',
    premiumtitletxt:
      'హిరణ్యగర్భ పుస్తకాన్ని పొందండి మరియు గర్భిణీ పిల్లల PQ, IQ, EQ మరియు SQ అభివృద్ధి కోసం రోజుకు 25+ కార్యకలాపాలు',
    helpno: 'హెల్ప్‌లైన్ నంబర్ : ',
    pay: 'పే',
    LMP: 'మీ చివరి నెలపూజ కాలాన్ని నమోదు చేయండి',
    EDD: 'మీ అంచనా లభించే జనన తేదీ నమోదు చేయండి',
  },
  ar: {
    welcome: 'أهلاً وسهلاً',
    welcometoh: 'أهلاً وسهلاً في هيرانياغاربه',
    subText: 'أكثر مجتمع موثوق للجاربهسانسكر في الهند',
    changeLanguage: 'تغيير اللغة',
    Hi: 'مرحباً',
    howCanHelp: 'كيف يمكننا مساعدتك؟',
    chatWithUs: 'الدردشة معنا',
    support: 'الدعم',
    enterYourEmail: 'أدخل بريدك الإلكتروني',
    enterYourPass: 'أدخل كلمة المرور',
    password6Digit: 'يجب أن تكون كلمة المرور مكونة من 6 أحرف على الأقل',
    pleaseValidEMail: 'يرجى إدخال بريد إلكتروني صالح',
    wesentOTP: 'لقد أرسلنا OTP إلى',
    ResendOTP: 'إعادة إرسال OTP',
    Email: 'البريد الإلكتروني',
    Password: 'كلمة المرور',
    loginwithotp: 'تسجيل الدخول باستخدام OTP',
    loginwithpass: 'تسجيل الدخول باستخدام كلمة المرور',
    loginwithwhatsapp: 'تسجيل الدخول باستخدام WhatsApp',
    loginwithmobile: 'تسجيل الدخول باستخدام البريد الإلكتروني',
    verifyEmail: 'تحقق من بريدك الإلكتروني',
    addPhoneNumber: 'أضف بريدك الإلكتروني. سنرسل لك رمز التحقق.',
    enterPassword: 'أدخل رقم هاتفك المسجل وكلمة المرور للوصول إلى التطبيق.',
    login: 'تسجيل الدخول',
    sendotp: 'إرسال OTP',
    Profile: 'الملف الشخصي',
    Premium: 'مميز',
    myProfile: 'ملفي الشخصي',
    ProductsPlans: 'المنتجات والخطط',
    MyOrder: 'طلباتي',
    changeLanguage: 'تغيير اللغة',
    PrivacyPolicy: 'سياسة الخصوصية',
    TermsCondition: 'الشروط والأحكام',
    Subscription: 'الشروط والأحكام الاشتراك',
    Logout: 'تسجيل الخروج من الحساب',
    Goodnoon: 'مساء الخير',
    Goodmorning: 'صباح الخير',
    Goodevening: 'مساء الخير',
    yourChild: 'أفضل استثمار يمكنك القيام به لطفلك ومستقبلك',
    setting: 'الإعدادات',
    signup: 'التسجيل',
    fullname: 'الاسم الكامل',
    enterYourFullname: 'أدخل اسمك الكامل',
    userMo: 'رقم الهاتف المحمول',
    enterusermo: 'أدخل رقم هاتفك المحمول',
    chooseyourePreferred: 'اختر لغتك المفضلة',
    chooseLanguage: 'اختر اللغة',
    bestinvestement: 'أفضل استثمار يمكنك القيام به من أجل',
    yourchild: 'طفلك، مستقبلك',
    gold: 'ذهب',
    silver: 'فضة',
    platinum: 'بلاتين',
    off: 'إيقاف',
    premiumtitletxt:
      'احصل على كتاب هيرانياغربا و 25+ نشاطًا يوميًا لتنمية PQ و IQ و EQ و SQ للأطفال الجدد',
    helpno: 'رقم الخط الساخن : ',
    pay: 'ادفع',
    LMP: 'أدخل آخر فترة حيض لك',
    EDD: 'أدخل تاريخ الولادة المتوقع',
  },
  es: {
    welcome: 'Bienvenido',
    welcometoh: 'Bienvenido a HiranyaGarbha',
    subText: 'La comunidad de Garbhsanskar en línea más confiable de la India',
    changeLanguage: 'Cambiar idioma',
    Hi: 'Hola',
    howCanHelp: '¿Cómo podemos ayudarte?',
    chatWithUs: 'Chatea con nosotros',
    support: 'Soporte',
    enterYourEmail: 'Introduce tu correo electrónico',
    enterYourPass: 'Introduce tu contraseña',
    password6Digit: 'La contraseña debe tener al menos 6 caracteres',
    pleaseValidEMail: 'Por favor, ingresa un correo electrónico válido',
    wesentOTP: 'Hemos enviado el OTP a',
    ResendOTP: 'Reenviar OTP',
    Email: 'Correo electrónico',
    Password: 'Contraseña',
    loginwithotp: 'Iniciar sesión con OTP',
    loginwithpass: 'Iniciar sesión con contraseña',
    loginwithwhatsapp: 'Iniciar sesión con WhatsApp',
    loginwithmobile: 'Iniciar sesión con correo electrónico',
    verifyEmail: 'Verifica tu correo electrónico',
    addPhoneNumber:
      'Añade tu correo electrónico. Te enviaremos un código de verificación.',
    enterPassword:
      'Introduce tu número de teléfono registrado y la contraseña para acceder a la aplicación.',
    login: 'Iniciar sesión',
    sendotp: 'Enviar OTP',
    Profile: 'Perfil',
    Premium: 'Premium',
    myProfile: 'Mi perfil',
    ProductsPlans: 'Productos y planes',
    MyOrder: 'Mis pedidos',
    changeLanguage: 'Cambiar idioma',
    PrivacyPolicy: 'Política de privacidad',
    TermsCondition: 'Términos y condiciones',
    Subscription: 'Términos y condiciones de suscripción',
    Logout: 'Cerrar sesión',
    Goodnoon: 'Buenas tardes',
    Goodmorning: 'Buenos días',
    Goodevening: 'Buenas noches',
    yourChild: 'La mejor inversión que puedes hacer para tu hijo, tu futuro',
    setting: 'Configuración',
    signup: 'Registrarse',
    fullname: 'Nombre completo',
    enterYourFullname: 'Introduce tu nombre completo',
    userMo: 'Número de móvil',
    enterusermo: 'Introduce tu número de móvil',
    chooseyourePreferred: 'Elige tu idioma preferido',
    chooseLanguage: 'Elegir idioma',
    bestinvestement: 'La mejor inversión que puedes hacer para',
    yourchild: 'Tu hijo, tu futuro',
    gold: 'Oro',
    silver: 'Plata',
    platinum: 'Platino',
    off: 'apagado',
    premiumtitletxt:
      'Obtén el libro Hiranyagarbha y más de 25 actividades diarias para el desarrollo PQ, IQ, EQ y SQ de los niños no nacidos',
    helpno: 'Número de ayuda: ',
    pay: 'Pagar',
    LMP: 'Ingresa tu última menstruación',
    EDD: 'Ingresa tu fecha estimada de parto',
  },
  fr: {
    welcome: 'Bienvenue',
    welcometoh: 'Bienvenue sur HiranyaGarbha',
    subText: "La communauté Garbhsanskar en ligne la plus fiable de l'Inde",
    changeLanguage: 'Changer de langue',
    Hi: 'Salut',
    howCanHelp: 'Comment pouvons-nous vous aider ?',
    chatWithUs: 'Discutez avec nous',
    support: 'Support',
    enterYourEmail: 'Entrez votre e-mail',
    enterYourPass: 'Entrez votre mot de passe',
    password6Digit: 'Le mot de passe doit comporter au moins 6 caractères',
    pleaseValidEMail: 'Veuillez entrer un e-mail valide',
    wesentOTP: 'Nous avons envoyé le OTP à',
    ResendOTP: 'Renvoyer OTP',
    Email: 'E-mail',
    Password: 'Mot de passe',
    loginwithotp: 'Se connecter avec OTP',
    loginwithpass: 'Se connecter avec mot de passe',
    loginwithwhatsapp: 'Se connecter avec WhatsApp',
    loginwithmobile: 'Se connecter avec e-mail',
    verifyEmail: 'Vérifiez votre e-mail',
    addPhoneNumber:
      'Ajoutez votre e-mail. Nous vous enverrons un code de vérification.',
    enterPassword:
      "Entrez votre numéro de mobile et votre mot de passe pour accéder à l'application.",
    login: 'Connexion',
    sendotp: 'Envoyer OTP',
    Profile: 'Profil',
    Premium: 'Premium',
    myProfile: 'Mon profil',
    ProductsPlans: 'Produits et plans',
    MyOrder: 'Ma commande',
    changeLanguage: 'Changer de langue',
    PrivacyPolicy: 'Politique de confidentialité',
    TermsCondition: 'Termes et conditions',
    Subscription: "Conditions d'abonnement",
    Logout: 'Se déconnecter',
    Goodnoon: 'Bon après-midi',
    Goodmorning: 'Bonjour',
    Goodevening: 'Bonsoir',
    yourChild:
      'Le meilleur investissement que vous puissiez faire pour votre enfant, votre avenir',
    setting: 'Paramètres',
    signup: "S'inscrire",
    fullname: 'Nom complet',
    enterYourFullname: 'Entrez votre nom complet',
    userMo: 'Numéro de portable',
    enterusermo: 'Entrez votre numéro de portable',
    chooseyourePreferred: 'Choisissez votre langue préférée',
    chooseLanguage: 'Choisir la langue',
    bestinvestement: 'Le meilleur investissement que vous pouvez faire pour',
    yourchild: 'Votre enfant, votre avenir',
    gold: 'Or',
    silver: 'Argent',
    platinum: 'Platine',
    off: 'éteint',
    premiumtitletxt:
      'Obtenez le livre Hiranyagarbha et 25+ activités quotidiennes pour le développement PQ, IQ, EQ et SQ des enfants à naître',
    helpno: "Numéro d'assistance : ",
    pay: 'Payer',
    LMP: 'Entrez votre dernier période menstruelle',
    EDD: 'Entrez votre date de livraison estimée',
  },
  pt: {
    welcome: 'Bem-vindo',
    welcometoh: 'Bem-vindo ao HiranyaGarbha',
    subText: 'A comunidade Garbhsanskar online mais confiável da Índia',
    changeLanguage: 'Mudar idioma',
    Hi: 'Oi',
    howCanHelp: 'Como podemos ajudar?',
    chatWithUs: 'Bate-papo conosco',
    support: 'Suporte',
    enterYourEmail: 'Digite seu e-mail',
    enterYourPass: 'Digite sua senha',
    password6Digit: 'A senha deve ter pelo menos 6 caracteres',
    pleaseValidEMail: 'Por favor, insira um e-mail válido',
    wesentOTP: 'Enviamos o OTP para',
    ResendOTP: 'Reenviar OTP',
    Email: 'E-mail',
    Password: 'Senha',
    loginwithotp: 'Entrar com OTP',
    loginwithpass: 'Entrar com senha',
    loginwithwhatsapp: 'Entrar com WhatsApp',
    loginwithmobile: 'Entrar com e-mail',
    verifyEmail: 'Verifique seu e-mail',
    addPhoneNumber: 'Adicione seu e-mail. Enviaremos um código de verificação.',
    enterPassword:
      'Digite seu número de celular registrado e a senha para acessar o aplicativo.',
    login: 'Entrar',
    sendotp: 'Enviar OTP',
    Profile: 'Perfil',
    Premium: 'Premium',
    myProfile: 'Meu perfil',
    ProductsPlans: 'Produtos e planos',
    MyOrder: 'Meus pedidos',
    changeLanguage: 'Mudar idioma',
    PrivacyPolicy: 'Política de privacidade',
    TermsCondition: 'Termos e condições',
    Subscription: 'Termos de assinatura',
    Logout: 'Sair da conta',
    Goodnoon: 'Boa tarde',
    Goodmorning: 'Bom dia',
    Goodevening: 'Boa noite',
    yourChild:
      'O melhor investimento que você pode fazer pelo seu filho, seu futuro',
    setting: 'Configurações',
    signup: 'Inscrever-se',
    fullname: 'Nome completo',
    enterYourFullname: 'Digite seu nome completo',
    userMo: 'Número de celular',
    enterusermo: 'Digite seu número de celular',
    chooseyourePreferred: 'Escolha seu idioma preferido',
    chooseLanguage: 'Escolher idioma',
    bestinvestement: 'O melhor investimento que você pode fazer para',
    yourchild: 'Seu filho, seu futuro',
    gold: 'Ouro',
    silver: 'Prata',
    platinum: 'Platina',
    off: 'desligado',
    premiumtitletxt:
      'Obtenha o livro Hiranyagarbha e mais de 25 atividades diárias para o desenvolvimento PQ, IQ, EQ e SQ de crianças não nascidas',
    helpno: 'Número de ajuda: ',
    pay: 'Pagar',
    LMP: 'Digite o seu último período menstrual',
    EDD: 'Digite a sua data estimada de parto',
  },
});

export default strings;
