export const actionTypes = {
   USER_DATA: 'USER_DATA',
   PREMIUM_DATA: 'PREMIUM_DATA',
   SET_LANGUAGE: 'SET_LANGUAGE',
   SET_UPDATE_INFO: 'SET_UPDATE_INFO',
   SET_UPDATE_DISMISSED: 'SET_UPDATE_DISMISSED',
   CHECK_UPDATE_START: 'CHECK_UPDATE_START',
   CHECK_UPDATE_SUCCESS: 'CHECK_UPDATE_SUCCESS',
   CHECK_UPDATE_ERROR: 'CHECK_UPDATE_ERROR',
 };
